name: CI

on:
  push:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --tests --benches --examples --all-features -- -D warnings

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Run unit tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --nocapture
      env: RUST_LOG=debug

  tests-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Run unit tests
      uses: actions-rs/cargo@v1
      with:
        command: test